"""
vless_installer/modules/hysteria2_watchdog.py
───────────────────────────────────────────────────────────────────────────────
Watchdog для Hysteria2: слежение за сервисом и авторестарт.

Архитектура:
  • Cron-скрипт (каждые 2 минуты) — не новый демон
  • Проверяет systemd-статус hysteria-server
  • При падении — restart + TG-уведомление
  • При повторных падениях — переключение на fallback-ноду (через балансировщик)
  • Ведёт счётчик падений в state.json для детекции loop-краша
  • Интеграция с Xray watchdog: при падении H2 → fallback на AWG

Точка входа из _core.py:
    from vless_installer.modules.hysteria2_watchdog import (
        h2_watchdog_run, h2_watchdog_install, h2_watchdog_remove,
        do_h2_watchdog_menu,
    )
───────────────────────────────────────────────────────────────────────────────
"""
from __future__ import annotations

import os
import sys
import time
from datetime import datetime
from pathlib import Path

from vless_installer.modules.hysteria2_common import (
    RED, GREEN, YELLOW, CYAN, BLUE, BOLD, DIM, NC,
    info, success, warn, error, log_to_file,
    _run, _load_h2_state, _save_h2_state,
    _tg_h2_event, _service_active, _systemctl,
    H2_SERVICE,
)
from vless_installer.modules.box_renderer import (
    _box_top, _box_row, _box_item, _box_item_exit, _box_sep,
    _box_bottom, _box_back,
)


_CRON_FILE    = Path("/etc/cron.d/hysteria2-watchdog")
_SCRIPT_FILE  = Path("/usr/local/bin/h2_watchdog.sh")
_WD_LOG       = Path("/var/log/hysteria-watchdog.log")
_RESTART_LIMIT = 5   # после N рестартов подряд → fallback


def _wd_log(msg: str) -> None:
    ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    try:
        with _WD_LOG.open("a") as f:
            f.write(f"[{ts}] {msg}\n")
    except Exception:
        pass
    log_to_file("INFO", f"H2 WD: {msg}")


# ── Логика watchdog ───────────────────────────────────────────────────────────
def h2_watchdog_run() -> None:
    """
    Одна итерация watchdog. Вызывается из cron каждые 2 минуты.
    Не блокирующий — завершается сразу после проверки.
    """
    h2 = _load_h2_state()
    if not h2.get("enabled", False):
        return

    active = _service_active(H2_SERVICE)

    if active:
        # Сервис жив — сбрасываем счётчик падений
        if h2.get("_wd_fail_count", 0) > 0:
            h2["_wd_fail_count"] = 0
            _save_h2_state(h2)
        return

    # Сервис упал
    h2["_wd_fail_count"] = h2.get("_wd_fail_count", 0) + 1
    fail_count = h2["_wd_fail_count"]
    _wd_log(f"Hysteria2 DOWN (#{fail_count})")
    _tg_h2_event("h2_down", f"Сервис упал (рестарт #{fail_count})")

    if fail_count >= _RESTART_LIMIT:
        # Слишком много падений подряд → пробуем fallback на другую ноду
        _wd_log(f"Достигнут лимит рестартов ({_RESTART_LIMIT}), пробую fallback")
        _tg_h2_event("h2_switch", f"Превышен лимит рестартов, fallback")
        try:
            from vless_installer.modules.hysteria2_balancer import h2_balancer_select_node
            from vless_installer.modules.hysteria2_transport import h2_transport_apply
            node = h2_balancer_select_node()
            active_ip = h2.get("_active_node_ip", "")
            if node and node.get("ip") != active_ip:
                h2_transport_apply(
                    exit_ip=node["ip"],
                    exit_port=node.get("ports", [443])[0],
                    auth_password=node.get("auth", ""),
                )
                h2["_active_node_ip"] = node["ip"]
                h2["_wd_fail_count"]  = 0
                _wd_log(f"Fallback → {node['ip']}")
            else:
                _wd_log("Нет альтернативных нод для fallback")
        except Exception as e:
            _wd_log(f"Fallback ошибка: {e}")
    else:
        # Обычный рестарт
        ok = _systemctl("restart", H2_SERVICE)
        time.sleep(3)
        if _service_active(H2_SERVICE):
            _wd_log("Hysteria2 перезапущен успешно")
            _tg_h2_event("h2_up", f"Сервис перезапущен (был DOWN #{fail_count})")
            h2["_wd_fail_count"] = 0
        else:
            _wd_log("Повторный запуск не помог")
            _tg_h2_event("h2_down", "Hysteria2 не смог перезапуститься")

    _save_h2_state(h2)


# ── Установка/удаление cron-watchdog ─────────────────────────────────────────
_SCRIPT_CONTENT = """\
#!/bin/bash
# H2 Watchdog — generated by VLESS Ultimate Installer
/usr/bin/python3 /opt/vless-installer/main.py --h2-watchdog-run 2>>/var/log/hysteria-watchdog.log
"""

_CRON_CONTENT = """\
# H2 Watchdog — VLESS Ultimate Installer
*/2 * * * * root /usr/local/bin/h2_watchdog.sh
"""


def h2_watchdog_install() -> None:
    """Устанавливает cron-watchdog для Hysteria2."""
    _SCRIPT_FILE.write_text(_SCRIPT_CONTENT)
    _SCRIPT_FILE.chmod(0o755)
    _CRON_FILE.write_text(_CRON_CONTENT)
    success(f"H2 Watchdog установлен → {_CRON_FILE}")
    log_to_file("INFO", "H2 watchdog installed")


def h2_watchdog_remove() -> None:
    """Удаляет cron-watchdog."""
    for f in (_CRON_FILE, _SCRIPT_FILE):
        if f.exists():
            f.unlink()
    success("H2 Watchdog удалён")
    log_to_file("INFO", "H2 watchdog removed")


def h2_watchdog_status() -> dict:
    return {
        "installed": _CRON_FILE.exists(),
        "service_active": _service_active(H2_SERVICE),
        "fail_count": _load_h2_state().get("_wd_fail_count", 0),
    }


# ── Меню ──────────────────────────────────────────────────────────────────────
def do_h2_watchdog_menu() -> None:
    """Интерактивное меню Watchdog H2."""
    while True:
        os.system("clear")
        print()
        h2  = _load_h2_state()
        wd  = h2.get("watchdog", {})
        _box_top("🔄  HYSTERIA2 — WATCHDOG / АВТОРЕСТАРТ")
        _box_row(f"  Watchdog: {'включён' if wd.get('enabled') else 'выключен'}  │  Падений: {CYAN}{wd.get('fail_count',0)}{NC}  │  Перезапусков: {CYAN}{wd.get('restart_count',0)}{NC}")
        _box_sep()
        _box_row()

        st = h2_watchdog_status()
        installed_str = f"{GREEN}установлен{NC}" if st["installed"] else f"{RED}не установлен{NC}"
        service_str   = f"{GREEN}активен{NC}" if st["service_active"] else f"{RED}DOWN{NC}"

        print(f"  Watchdog cron: {installed_str}")
        print(f"  Сервис H2:     {service_str}")
        print(f"  Падений подряд: {YELLOW}{st['fail_count']}{NC}")
        print()
        _box_item("1", f"Установить Watchdog  {DIM}(cron каждые 2 мин){NC}")
        _box_item("2", "Удалить Watchdog")
        _box_item("3", "Запустить проверку вручную сейчас")
        _box_item("4", "Показать лог Watchdog")
        _box_item("5", "Сбросить счётчик падений")
        _box_row()
        _box_item_exit("Q", "← Назад")
        _box_bottom()

        try:
            ch = input(f"{CYAN}Выбор:{NC} ").strip().upper()
        except KeyboardInterrupt:
            break

        if ch == "1":
            h2_watchdog_install()
            input(f"\n{BLUE}Нажмите Enter...{NC}")
        elif ch == "2":
            h2_watchdog_remove()
            input(f"\n{BLUE}Нажмите Enter...{NC}")
        elif ch == "3":
            h2_watchdog_run()
            success("Проверка завершена")
            input(f"\n{BLUE}Нажмите Enter...{NC}")
        elif ch == "4":
            if _WD_LOG.exists():
                lines = _WD_LOG.read_text().splitlines()[-40:]
                print("\n".join(lines))
            else:
                warn("Лог пуст")
            input(f"\n{BLUE}Нажмите Enter...{NC}")
        elif ch == "5":
            h2 = _load_h2_state()
            h2["_wd_fail_count"] = 0
            _save_h2_state(h2)
            success("Счётчик сброшен")
            input(f"\n{BLUE}Нажмите Enter...{NC}")
        elif ch == "Q":
            break
        else:
            time.sleep(0.5)


"""
ПРИМЕР ВЫЗОВА из _core.py / main.py:
    from vless_installer.modules.hysteria2_watchdog import (
        h2_watchdog_run, h2_watchdog_install, do_h2_watchdog_menu,
    )

    # Из cron / CLI --h2-watchdog-run:
    h2_watchdog_run()

    # Установить:
    h2_watchdog_install()

    # Интерактивно:
    do_h2_watchdog_menu()
"""
